
  development:
    adapter: postgresql
    encoding: unicode
    database: dryule_dev
    username: development
    password: development
    host: localhost
    template: template0


  test:
    adapter: postgresql
    encoding: unicode
    database: dryule_test
    username: test
    password: test
    host: localhost
    template: template0

  staging:
    adapter: postgresql
    encoding: unicode
    database: tbc
    username: tbc
    password: tbc
    host: tbc

  production:
    adapter: postgresql
    encoding: unicode
    database: dryule_com
    username: yule
    password: DBPa$$wordMajsn16
    host: localhost
