
  development:
    adapter: postgresql
    encoding: unicode
    database: dryule_dev
    username: development
    password: development
    host: localhost
    template: template0

  test:
    adapter: sqlite3
    database: ":memory:"
    verbosity: quiet

  staging:
    adapter: postgresql
    encoding: unicode
    database: tbc
    username: tbc
    password: tbc
    host: tbc

  production:
    adapter: postgresql
    encoding: unicode
    database: dryule_com
    username: yule
    password: DBPa$$wordMajsn16
    host: localhost
